### ISSUE TITLE
error during preprocessing

### ISSUE THREAD

**Issue by frenkiboy** [jkobject/scPRINT#9] opened 2024-08-16 11:50 UTC
The following code:

```
adata = sc.read_10x_mtx(os.path.join(path_data,"filtered_gene_bc_matrices/hg19"))
adata.obs["organism_ontology_term_id"] = "NCBITaxon:9606"
preprocessor = Preprocessor(do_postp=False, organisms="NCBITaxon:9606")
adata = preprocessor(adata)
```

gives the following error

```
AttributeError                            Traceback (most recent call last)
Cell In[66], line 1
----> 1 adata = preprocessor(adata)

File ~/bin/mamba/miniforge/envs/scprint/lib/python3.10/site-packages/scdataloader/preprocess.py:187, in Preprocessor.__call__(self, adata)
    184     sc.pp.filter_cells(adata, min_counts=self.filter_cell_by_counts)
    185 # if lost > 50% of the dataset, drop dataset
    186 # load the genes
--> 187 genesdf = data_utils.load_genes(adata.obs.organism_ontology_term_id.iloc[0])
    189 if prevsize / adata.shape[0] > self.maxdropamount:
    190     raise Exception(
    191         "Dataset dropped due to low expressed genes and unexpressed cells: factor of "
    192         + str(prevsize / adata.shape[0])
    193     )

File ~/bin/mamba/miniforge/envs/scprint/lib/python3.10/site-packages/scdataloader/utils.py:361, in load_genes(organisms)
    358     organisms = [organisms]
    359 for organism in organisms:
    360     genesdf = bt.Gene.filter(
--> 361         organism_id=bt.Organism.filter(ontology_id=organism).first().id
    362     ).df()
    363     genesdf = genesdf.drop_duplicates(subset="ensembl_gene_id")
    364     genesdf = genesdf.set_index("ensembl_gene_id").sort_index()
```

**Comment by jkobject** [comment] 2024-08-16 12:24
Hey, sorry for the issue,

Ok, so as of now you need to have an obs column named organism_onotology_term_id in your anndata. Do you have one and what does it contain?

**Comment by frenkiboy** [comment] 2024-08-16 12:48
Tnx for the prompt response!

Here is the output:

```
In [18]: adata[0].obs.organism_ontology_term_id.iloc[0]
    ...: 
Out[18]: 'NCBITaxon:9606'
```

**Comment by jkobject** [comment] 2024-08-16 16:15
Cool I see and did you populate your lamin ontologies? You need to use this function from scdataloader. I think it is in the FAQ in the readme. Let me know.

**Comment by hanjun98** [comment] 2024-08-19 02:05
Hi, JK, I have a same issue! 
First, I think the problem is caused by my anndata, so I used your tutorial toydata("prostate_adata")
But, I have a same issue like that 
![Screenshot 2024-08-19 at 10 51 12 AM](https://github.com/user-attachments/assets/ec0c08ca-e9e5-48d1-8af5-c992b36918da)

Maybe, I think this problem about lamin.ai,  nevertheless I connected laminai correctly(?),'bionty' couldn't query from lamin.ai(?)

Do you have any opinion? or solution? about this issue

**Comment by jkobject** [comment] 2024-08-19 14:06
Hello, yes!

I have added this in the readme now. Let me know if you see it. 

You have to populate the ontologies. Basically lamindb creates a db of stuff like genes and cell types. You have access to one with bionty.public() already but with scPRINT you need to load them into your own db with the populate ontology function I show in the readme. 

Let me know if you see it. 

Next week I will add more explanation about lamin and the creation of a local db!

Best,

**Comment by kavithakrishna1** [comment] 2024-08-21 07:36
Hi @jkobject, I have followed the readme page on scDataLoader. I first did this, then got an error that 

`AttributeError: module 'scdataloader.utils' has no attribute 'populate_ontologies'. Did you mean: 'populate_my_ontology'?`

```python
from scdataloader import utils
utils.populate_ontologies() # this might take from 5-20mins
``` 

Then I ran `utils.populate_my_ontology()` which gives me:

```python
💡 returning existing CellType record with same name: 'unknown'
💡 returning existing Organism record with same name: 'unknown'
❗ did not create Phenotype record for 1 non-validated ontology_id: 'PATO:0000384'
❗ did not create Phenotype record for 1 non-validated ontology_id: 'PATO:0000383'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/directflow/SCCGGroupShare/projects/kavkri/.conda/envs/scprint-env/lib/python3.10/site-packages/scdataloader/utils.py", line 440, in populate_my_ontology
    ln.save(records)
  File "/directflow/SCCGGroupShare/projects/kavkri/.conda/envs/scprint-env/lib/python3.10/site-packages/lamindb/_save.py", line 78, in save
    non_artifacts_old, non_artifacts_new = partition(
  File "/directflow/SCCGGroupShare/projects/kavkri/.conda/envs/scprint-env/lib/python3.10/site-packages/django/utils/functional.py", line 450, in partition
    results[predicate(item)].append(item)
  File "/directflow/SCCGGroupShare/projects/kavkri/.conda/envs/scprint-env/lib/python3.10/site-packages/lamindb/_save.py", line 79, in <lambda>
    lambda r: r._state.adding or r.pk is None, non_artifacts
AttributeError: 'NoneType' object has no attribute '_state'
```

**Comment by frenkiboy** [comment] 2024-08-21 16:02
I get the same error as above

**Comment by jkobject** [comment] 2024-08-22 10:06
Sorry for the issue, 
I pushed an update that should debug it, either git pull scdataloader if you were using a dev installation or update it with pip, I also updated the readmes slightly to give more information on the topic.

**Comment by jkobject** [comment] 2024-08-22 10:07
Let me know if it works on your end and if you encounter any additional issues. I tried to thoroughly test the package, but you are the first person other than me to use it, so some issues are to be expected.

**Comment by frenkiboy** [comment] 2024-08-22 11:29
Hey Jérémie,

Thank you so much for your prompt replies!

I did the following:

```
pip install git+https://github.com/jkobject/scDataLoader@dev
```

then upon
```
from scprint import scPrint
```

I get the following error:
![image](https://github.com/user-attachments/assets/1bcc00e0-59ce-412c-8b6f-152c08b03c2a)

Should I install an updated version of lamindb?

**Comment by jkobject** [comment] 2024-08-22 11:31
Oh no don't use the dev branch. It is not up to date please follow the install from the readmes

**Comment by kavithakrishna1** [comment] 2024-08-22 11:59
@frenkiboy I installed scdataloader like `pip install scdataloader`

Then upgraded now with `pip install scdataloader --upgrade`

@jkobject I reran with the prostate dataset used in the [tutorial](https://github.com/jkobject/scPRINT/blob/main/docs/notebooks/cancer_usecase.ipynb) 
There was 27370 genes to begin with and all genes were removed.

```python
cx_dataset = ln.Collection.using(instance="laminlabs/cellxgene").filter(name="cellxgene-census", version='2023-12-15').one()
adata = cx_dataset.artifacts.filter(key='cell-census/2023-12-15/h5ads/574e9f9e-f8b4-41ef-bf19-89a9964fd9c7.h5ad').one().load()
adata.obs.drop(columns="is_primary_data", inplace=True)
preprocessor = Preprocessor(do_postp=False)
adata = preprocessor(adata)
``` 

<img width="1149" alt="Screenshot 2024-08-22 at 9 57 38 PM" src="https://github.com/user-attachments/assets/8d8a8c5c-fcc6-4bb0-895f-8ef0a0ac9780">

**Comment by jkobject** [comment] 2024-08-22 12:03
@frenkiboy Oh no don't use the dev branch. It is not up to date please follow the install from the readmes

**Comment by jkobject** [comment] 2024-08-22 12:04
Hmm this is weird. Did you populate the ontologies?

**Comment by jkobject** [comment] 2024-08-22 12:05
What happens when you do 
```
bt.Genes.filter().df()
```

**Comment by kavithakrishna1** [comment] 2024-08-22 12:06
Ah ofc, my bad! I forgot to rerun `utils.populate_my_ontology()`
It is running now. I will let you know how it goes.

**Comment by kavithakrishna1** [comment] 2024-08-26 05:25
Okay that now works. I downloaded the checkpoints from hugging face and loaded them. I am up to the embedder in this tutorial https://github.com/jkobject/scPRINT/blob/main/docs/notebooks/cancer_usecase.ipynb

I first ran
```python
adata, metrics = embedder(model, adata, cache=False, output_expression="none")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Embedder.__call__() got an unexpected keyword argument 'output_expression'
``` 

Then I ran with "output_expression" parameter removed. However it stops and automatically quits my python terminal. (I am running python interactively inside a conda env). I am wondering if this is a memory issue (currently using 1 GPU with 164GB). Should I try increasing the memory?
```python
adata, metrics = embedder(model, adata, cache=False)
0%|                                                                                                                                                          | 0/1304 [00:00<?, ?it/s]                                                                                                                                                                                
```

**Comment by jkobject** [comment] 2024-08-26 14:59
I am looking at it now. The fact that you don't have output expression is weird and makes me think you might not have the latest version?

So I understand, what is happening is that nothing seems to be happening on your side? I am using much less memory on my side so I don't think that is the issue... 

Did you get any error message saying that it was not using flash attention while running on of the cells?

**Comment by kavithakrishna1** [comment] 2024-08-27 02:38
The readme notes says to use flashattention2. Is it okay to use flashattention1? flash-attention2 requires 11.6 and above, but my CUDA Version is 11.4.

**Comment by jkobject** [comment] 2024-08-27 10:37
The code that the model is running is flash attention 2. It is not a dependency but part of the model. ScPRINT does it through triton. I have never tested scPRINT on 11.4.. you would have to use pdb and check if the model.predict() function gets called within the embedder class. Also can you check if the GPU memory gets used?

Also you can set the input context to 200 and the minibatch size to 1 to check what happens.. maybe it is not using the GPU. (These are parameters of the embedder class)

**Comment by hanjun98** [comment] 2024-09-04 03:03
> I just installed scprint last week or 2 through pip. Have there been updates since then?
> 
> The readme notes says to use flashattention2. Is it okay to use flashattention1? flash-attention2 requires CUDA 11.6 and above, but my CUDA Version is 11.4.

I have a similar issue.
Readme Refers that "I was able to test it with nvidia 11.7, 11.8, 12.2." 
But my nvidia(cuda) version is 12.0. I think I have similar problem when I install scvi, so I solved this problem through same way for installing scvi before. 

here is my code

`mamba create -n scprint python=3.10 jupyter ipykernel
pip install pandas PyYAML scipy
mamba install jaxlib=*=*cuda* jax cuda-nvcc -c conda-forge -c nvidia
pip install scprint[dev]
lamin login <email> --key <API-key>
lamin init --storage <folder-name-where-lamin-data-will-be-stored> --schema bionty
`
You can see thing associated with this problem in [https://github.com/scverse/scvi-tools/issues/2333]

**Comment by jkobject** [comment] 2024-09-04 08:10
Hello, 

you have the same issue as @kavithakrishna1 ?
Is it this one? where it hangs forever?
> adata, metrics = embedder(model, adata, cache=False)
> 0%|                                                           | 0/1304 [00:00<?, ?it/s] 
> (quits python terminal here)

**Comment by jkobject** [comment] 2024-09-04 10:16
Ok since multiple issues are starting to be mentioned in the same place I have created a new one for @hanjun98 and @kavithakrishna1 which seem to be related to cuda / nvidia and flashattention installation. I will close this one about preprocessing since it seems to have been solved. @frenkiboy should confirm

**Closed by jkobject** 2024-09-04 10:16 UTC
Labels: bug, help wanted
